In [147]:
import pandas as pd
import numpy as np
import seaborn as sns

In [148]:
#ham mane good ,spam mane bad
# 1 =spam
# 0 =ham

In [149]:
df=pd.read_csv('/content/emails.csv')

In [150]:
df['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [151]:
df.duplicated().sum()

33

In [152]:
df.drop_duplicates(inplace=True)

In [153]:
df.duplicated().sum()

0

In [154]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [155]:
#separate x and y
x= df.text.values
y=df.spam.values

In [156]:
#split dataset
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y, train_size=0.2)


In [157]:
#Data Processing
from sklearn.feature_extraction.text import CountVectorizer

In [158]:
cv=CountVectorizer()

In [159]:
x_train=cv.fit_transform(xtrain)

In [160]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [9, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [161]:
#ML Algorithm
#naive bayes used for classification problem,It is highly used in text classification.
#Types: Gaussian Naive Bayes classifier,Multinomial Naive Bayes,Bernoulli Naive Bayes

In [162]:
#ay type data jonno multinomialNB besi effective

In [163]:
from sklearn.naive_bayes import MultinomialNB

In [164]:
model=MultinomialNB()

In [165]:
model.fit(x_train,ytrain)

MultinomialNB()

In [166]:
x_test=cv.transform(xtest)

In [167]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]])

In [168]:
model.score(x_test,ytest)

0.9885864793678666

In [187]:
emails=['your are looking a expertise so we can hire you','but you need to fillup this for win  the lottery this oppportunity.']

In [188]:
cv_emails=cv.transform(emails)
cv_emails.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [189]:
model.predict(cv_emails)


array([0, 1])