In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
#ham mane valo ,spam mane kharp
# 1 =spam
# 0 =ham

In [3]:
df=pd.read_csv('/content/emails.csv')

In [9]:
df['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [11]:
df.duplicated().sum()

33

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df.duplicated().sum()

0

In [16]:
df.isnull().sum()

text    0
spam    0
dtype: int64

In [17]:
#separate x and y
x= df.text.values
y=df.spam.values

In [22]:
#split dataset
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y, train_size=0.2)


In [28]:
#Data Processing
from sklearn.feature_extraction.text import CountVectorizer

In [29]:
cv=CountVectorizer()

In [69]:
x_train=cv.fit_transform(xtrain)

AttributeError: 'csr_matrix' object has no attribute 'lower'

In [32]:
xtrain.toarray()

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [7, 0, 0, ..., 0, 0, 0]])

In [ ]:
#ML Algorithm
#naive bayes used for classification problem,It is highly used in text classification.
#Types: Gaussian Naive Bayes classifier,Multinomial Naive Bayes,Bernoulli Naive Bayes

In [ ]:
#ay type data jonno multinomialNB besi effective

In [33]:
from sklearn.naive_bayes import MultinomialNB

In [34]:
model=MultinomialNB()

In [37]:
model.fit(xtrain,ytrain)

MultinomialNB()

In [41]:
x_test=cv.transform(xtest)

In [43]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [44]:
model.score(x_test,ytest)

0.9866110623353819

In [46]:
emails=['hey i am looking a nice man like you','but you need to fillup this for win this oppportunity.']

In [67]:
cv_emails=cv.transform(emails)
cv_emails.toarray()

array([[1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1]])

In [68]:
model.predict(cv_emails)


ValueError: X has 15 features, but MultinomialNB is expecting 17206 features as input.